### PR TITLE
Anti false/anti true + unit.blocked instead of parse_rule = false (or something like this)

### PR DESCRIPTION
**Pull request by Dzhake**
so uhhh title? i hope you can understand everything lol. i think you should look in game/scene.lua line about 1350? false and true code there. Also you can remake them as fols and tru so they won't conflict with lua's ones.

### CODE REVIEW

**Comment by Dzhake** [comment]
This is only for my mod, correct? if no, then i will combine all my known bugs in one pull request.

**Comment by Adrthegamedev** [comment]
You've done, uh, a lot more than what the title says, including adding way too much sprites, overwriting the readme file, and breaking the obscure inbuilt mod support. yeah no way this is getting merged in its current state

**Comment by Dzhake** [comment]
uhhh i don't wanna make this merged? Also, what is wrong with overwriting readme file? And why way too much sprites? Yeah, i know about inbuilt mod support, but i didn't like it, so i made my own mod support

**Comment by Dzhake** [comment]
Looks like idk what is pull request lol.

**Comment by Dzhake** [comment]
I thought it's like: "this is bugged, i should fix it. Maybe you know how to fix it? pls help me."

**Comment by Dzhake** [comment]
Maybe i should use "issues" tab? hm..

**Comment by Adrthegamedev** [comment]
> Maybe i should use "issues" tab? hm..

No, the issues tab is for issues in the _regular_ codebase, not any modded ones.

**Pull request closed without merging**
